version: "3.9"

services:
  db:
    image: postgres:14.4-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/envs/.env
    ports:
      - 5432
    container_name: lifestore_db
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /backend/start.sh
    volumes:
      - ./backend:/backend
    ports:
      - 8000
    env_file:
      - ./config.env
    depends_on:
      - db
    restart: unless-stopped
    container_name: lifestore_backend

  nginx:
    build: 
      context: .
      dockerfile: ./frontend/nginx/Dockerfile
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
      - ./backend/config/static/:/usr/share/nginx/html/static/
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped


volumes:
  postgres_data: {}
